trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: 'InvoiceApi'

- task: DotNetCoreCLI@2
  displayName: 'Unit tests'
  inputs:
    command: 'test'
    arguments: 'UnitTests'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '-c $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishPipelineArtifact@1
  displayName: 'Create the artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: '$(ArtifactName)-$(Build.BuildId)'
